<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260927153325 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Initial schema';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE app_user (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              username VARCHAR(180) NOT NULL,
              password VARCHAR(255) NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX UNIQ_88BDF3E9F85E0677 ON app_user (username)');
        $this->addSql(<<<'SQL'
            CREATE TABLE event (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              event_id VARCHAR(32) NOT NULL,
              received_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              occurred_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              level VARCHAR(16) NOT NULL,
              platform VARCHAR(64) NOT NULL,
              environment VARCHAR(64) DEFAULT NULL,
              release VARCHAR(200) DEFAULT NULL,
              transaction VARCHAR(200) DEFAULT NULL,
              message TEXT DEFAULT NULL,
              exception JSONB NOT NULL,
              tags JSONB NOT NULL,
              contexts JSONB NOT NULL,
              request JSONB DEFAULT NULL,
              user_data JSONB DEFAULT NULL,
              extra JSONB NOT NULL,
              project_id INT NOT NULL,
              issue_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX event_issue_received_at ON event (issue_id, received_at)');
        $this->addSql('CREATE INDEX event_received_at ON event (received_at)');
        $this->addSql('CREATE UNIQUE INDEX event_project_event_id ON event (project_id, event_id)');
        $this->addSql('CREATE INDEX IDX_3BAE0AA7166D1F9C ON event (project_id)');
        $this->addSql('CREATE INDEX IDX_3BAE0AA75E7AA58C ON event (issue_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE issue (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              fingerprint VARCHAR(64) NOT NULL,
              title VARCHAR(255) NOT NULL,
              culprit VARCHAR(255) DEFAULT NULL,
              level VARCHAR(16) NOT NULL,
              status VARCHAR(16) NOT NULL,
              first_seen TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              last_seen TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              event_count INT NOT NULL,
              last_release VARCHAR(200) DEFAULT NULL,
              last_notified_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              project_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX issue_project_status_last_seen ON issue (project_id, status, last_seen)');
        $this->addSql('CREATE UNIQUE INDEX issue_project_fingerprint ON issue (project_id, fingerprint)');
        $this->addSql('CREATE INDEX IDX_12AD233E166D1F9C ON issue (project_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE issue_daily_count (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              day DATE NOT NULL,
              count INT NOT NULL,
              issue_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX issue_daily_count_day ON issue_daily_count (day)');
        $this->addSql('CREATE UNIQUE INDEX issue_daily_count_issue_day ON issue_daily_count (issue_id, day)');
        $this->addSql('CREATE INDEX IDX_67B370125E7AA58C ON issue_daily_count (issue_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE project (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              name VARCHAR(100) NOT NULL,
              slug VARCHAR(100) NOT NULL,
              public_key VARCHAR(32) NOT NULL,
              allowed_origins JSONB NOT NULL,
              retention_days INT NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2FB3D0EE989D9B62 ON project (slug)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2FB3D0EE66F9D463 ON project (public_key)');
        $this->addSql(<<<'SQL'
            CREATE TABLE messenger_messages (
              id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              body TEXT NOT NULL,
              headers TEXT NOT NULL,
              queue_name VARCHAR(190) NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (
              queue_name, available_at, delivered_at,
              id
            )
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              event
            ADD
              CONSTRAINT FK_3BAE0AA7166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              event
            ADD
              CONSTRAINT FK_3BAE0AA75E7AA58C FOREIGN KEY (issue_id) REFERENCES issue (id) ON DELETE CASCADE NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              issue
            ADD
              CONSTRAINT FK_12AD233E166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              issue_daily_count
            ADD
              CONSTRAINT FK_67B370125E7AA58C FOREIGN KEY (issue_id) REFERENCES issue (id) ON DELETE CASCADE NOT DEFERRABLE
        SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE event DROP CONSTRAINT FK_3BAE0AA7166D1F9C');
        $this->addSql('ALTER TABLE event DROP CONSTRAINT FK_3BAE0AA75E7AA58C');
        $this->addSql('ALTER TABLE issue DROP CONSTRAINT FK_12AD233E166D1F9C');
        $this->addSql('ALTER TABLE issue_daily_count DROP CONSTRAINT FK_67B370125E7AA58C');
        $this->addSql('DROP TABLE app_user');
        $this->addSql('DROP TABLE event');
        $this->addSql('DROP TABLE issue');
        $this->addSql('DROP TABLE issue_daily_count');
        $this->addSql('DROP TABLE project');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
